spring:
  application:
    name: Smart-Gateway

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    queue:
      light:
        name: ${LIGHT_NAME:queue_sensor_light}
      humidity:
        name: ${HUMIDITY_NAME:queue_sensor_humidity}
      temperature:
        name: ${TEMPERATURE_NAME:queue_sensor_temperature}

grpc:
  devices:
    actuator_temperature:
      host: localhost
      port: 50051
    actuator_light:
      host: localhost
      port: 50052
    actuator_humidity:
      host: localhost
      port: 50053



