spring:
  application:
    name: Smart-Gateway

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update  # Ou "create", "create-drop", "validate" dependendo do comportamento desejado

  datasource:
    url: jdbc:h2:mem:mydb
    #url: jdbc:h2:file:/data/demo #system file
    username: sa
    password: password
    driverClassName: org.h2.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    queue:
      light:
        name: ${LIGHT_NAME:queue_sensor_light}
      humidity:
        name: ${HUMIDITY_NAME:queue_sensor_humidity}
      temperature:
        name: ${TEMPERATURE_NAME:queue_sensor_temperature}
