spring:
  application:
    name: Smart-Gateway
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

  datasource:
    url: jdbc:h2:mem:mydb
    #url: jdbc:h2:file:/data/demo #system file
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

  rabbitmq:
    queue:
      lamp:
        name: ${LAMP_NAME:queue-sensor-lamp}